spring:
  mail:
    host: smtp.163.com
    username: 188****3092@163.com
    password: PASM*****MBMM
    # 需要去对应网易开启邮件服务 获取到对应的密码，不是自己的邮箱密码
    default-encoding: utf-8
    properties:
      mail:
        smtp.auth:true
  thymeleaf:
    mode: LEGACYHTML5
    cache:  false

mail.form: 188****3092@163.com

